on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432
    services:
      postgres:
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        image: postgres
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ github.token }}
      - name: Setup Rust toolchain
        run: rustup show
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: build

      - name: Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --locked -- -D warnings

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --locked --release