on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432
    services:
      postgres:
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        image: postgres
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Rust toolchain
        run: rustup show
      - name: Install SQLx CLI
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: sqlx-cli
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: build

      - name: Prepare CI database
        run: sqlx migrate run

      - name: Check .sqlx file
        run: sqlx prepare --check
      - if: failure()
        run: echo 'Please run `sqlx prepare` to update the .sqlx file'

      - name: Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --locked -- -D warnings

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --locked --release